src/IMS.Web/Areas/Repair/Controllers/CommonController.cs
using AutoMapper;
using IMS.Data.DAL;
using IMS.Model.Entity;
using IMS.Web.Dto;
using System.Collections.Generic;
using System.Web.Mvc;

namespace IMS.Web.Areas.Repair.Controllers
{
    public class CommonController : Controller
    {
        //
        // GET: /Partial/

        public ActionResult SubSystem()
        {
            return PartialView();
        }
        public ActionResult EngineerSelect()
        {
            return PartialView();
        }

        public ActionResult SearchBar()
        {
            return PartialView();
        }
        public JsonResult GetSubSystemList(int lev, int parentId)
        {
            var res = new JsonResult<List<SubSystemDto>>();
            if (lev != -1)
            {
                var subsystemEntityList = CommonDAL.GetSubSystemList(lev, parentId);
                var list = Mapper.Map<List<SubSystem>, List<SubSystemDto>>(subsystemEntityList);
                if (list != null)
                {
                    res.flag = true;
                    res.data = list;
                }
            }
            return Json(res);
        }
        public ActionResult GetTeamOrEngrName(string type, string teamName)
        {
            var res = new JsonResult<List<EngineerDto>>();
            List<Users> userList = CommonDAL.GetTeamOrEngrName(type, teamName);
            var list = Mapper.Map<List<Users>, List<EngineerDto>>(userList);
            if (list != null)
            {
                res.flag = true;
                res.data = list;
            }
            return Json(res);
        }

        public JsonResult GetWorkSectionNameList()
        {
            var res = new JsonResult<List<DeviceDto>>();
            List<Device> deviceList = CommonDAL.GetWorkSectionNameList();
            var list = Mapper.Map<List<Device>, List<DeviceDto>>(deviceList);
            if (list != null)
            {
                res.flag = true;
                res.data = list;
            }
            return Json(res);
        }

        public JsonResult GetDeviceNamesBySection(string sectionName)
        {
            var res = new JsonResult<List<DeviceDto>>();
            List<Device> deviceList = CommonDAL.GetDevicesBySection(sectionName);
            var list = Mapper.Map<List<Device>, List<DeviceDto>>(deviceList);
            if (list != null)
            {
                res.flag = true;
                res.data = list;
            }
            return Json(res);
        }
    }
}

src/IMS.Web/Areas/Repair/Controllers/RepairController.cs
using AutoMapper;
using IMS.Data.DAL;
using IMS.Model.Entity;
using IMS.Web.Dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using IMS.Json;
using System.Web.Mvc;
using IMS.Enume;
using IMS.Extensions;

namespace IMS.Web.Areas.Repair.Controllers
{
    public class RepairController : Controller
    {
        // GET: Repair
        RepairDAL repairDAL = new RepairDAL();
        public ActionResult AllApplications()
        {
            return View();
        }
        //[HttpPost]
        public ActionResult GetAllApplications(int limit, int offset, string sectionName, string deviceNo, string beginTime, string endTime, string ordername, string order)
        {
            //角色 role 从当前登录的用户信息里获取
            string role = string.Empty;
            string orderName = ordername == "DeviceShortName" ? "DeviceNo" : ordername;
            Expression<Func<RepairApplication, bool>> exp = item => !item.IsDeleted;
            if (!String.IsNullOrEmpty(deviceNo) && !String.Equals(deviceNo, "-1"))
            {
                exp = exp.And(g => g.DeviceNo == deviceNo);
            }
            if (!String.IsNullOrEmpty(beginTime))
            {
                DateTime _beginTime = Convert.ToDateTime(beginTime);
                exp = exp.And(g => g.BeginTime > _beginTime);
            }
            if (String.Equals(role, "Worker"))
            {
                exp = exp.And(g => g.Status == CurrentStatus.待审核.ToString())
                         .Or(g => g.Status == CurrentStatus.已驳回.ToString());
            }
            if (String.Equals(role, "Engineer"))
            {
                exp = exp.And(g => g.Status != CurrentStatus.待审核.ToString())
                         .And(g => g.Status != CurrentStatus.已驳回.ToString())
                         .And(g => g.Status != CurrentStatus.已总结.ToString());
            }
            if (!String.IsNullOrEmpty(endTime))
            {
                DateTime _endTime = Convert.ToDateTime(endTime);
                exp = exp.And(g => g.BeginTime < _endTime);
            }
            var applicationList = repairDAL.ApplicationsByRole(sectionName, orderName, order, exp); 
            List<ApplicationDto> ApplicationDtoList = Mapper.Map<List<RepairApplication>, List<ApplicationDto>>(applicationList);
            if (ApplicationDtoList != null)
            {
                var total = ApplicationDtoList.Count;
                var rows = ApplicationDtoList.Skip(offset).Take(limit).ToList();
                var result = new { total = total, rows = rows };
                return Content(result.ToJsonString());
            }
            else
                return Json("");
        }

        #region 操作工
        public ActionResult NewApplication()
        {
            return View();
        }
        [HttpPost]
        public void CreatApplication()
        {
            ApplicationDto applicationDto = new ApplicationDto();
            applicationDto.DeviceNo = Request.Params["deviceNo"];
            applicationDto.BeginTime = Convert.ToDateTime(Request.Params["beginTime"]);
            applicationDto.FailureAppearance = Request.Params["failureAppearance"];
            applicationDto.FailureDescription = Request.Params["failureDescription"];
            applicationDto.FirstLocation = Request.Params["fstLevFailureLocation"];
            applicationDto.SecondLocation = Request.Params["secLevFailureLocation"];
            applicationDto.ThirdLocation = Request.Params["thiLevFailureLocation"];
            applicationDto.FailureType = Request.Params["failureType"];
            applicationDto.ApplicantId = "报告人A";
            applicationDto.ApplicationTime = DateTime.Now;
            applicationDto.Status = "待审核";
            var application = Mapper.Map<ApplicationDto, RepairApplication>(applicationDto);
            repairDAL.InsertNewApplication(application);//这个地方应该有结果判定，但是这个页面不重要不做了
        }
        [HttpPost]
        public ActionResult ModifyApplication()
        {
            ApplicationDto repairApplicationVM = new ApplicationDto();
            int id = Convert.ToInt32(Request.Params["applicationId"]);
            string appearance = Request.Params["failureAppearance"];
            string description = Request.Params["failureDescription"];
            string firstLocation = Request.Params["fstLevFailureLocation"];
            string secondLocation = Request.Params["secLevFailureLocation"];
            string thirdLocation = Request.Params["thiLevFailureLocation"];
            string failureType = Request.Params["failureType"];
            bool result = repairDAL.UpdateApplication(id, appearance, description, firstLocation, secondLocation, thirdLocation, failureType);
            if (result)
            {
                return Content(new { msg = "成功", status = "success" }.ToJsonString());
            }
            else
            {
                return Content(new { msg = "失败", status = "failed" }.ToJsonString());
            }

        }
        [HttpPost]
        public ActionResult DeleteApplication(int applicationId)
        {
            var result = repairDAL.DeleteApplicationById(applicationId);
            if (result)
            {
                return Content(new { msg = "删除成功", status = "success" }.ToJsonString());
            }
            else
            {
                return Content(new { msg = "删除失败", status = "failed" }.ToJsonString());
            }
        }

        #endregion

        #region 维修申请处理---管理员
        public ActionResult Dispatch()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dispatch(int applicationId, string workType, int engineerId, string instruction)
        {
            bool result = false;
            DispatchDto dispatchDto = new DispatchDto();
            dispatchDto.Instruction = instruction;
            dispatchDto.Engineer = engineerId;
            dispatchDto.Dispatcher = 9999;
            dispatchDto.CreatTime = DateTime.Now;
            Dispatch dispatch = null;
            DiagnoseDispatch diagnoseDispatch = null;
            if (String.Equals(workType, "维修"))
            {
                dispatch = Mapper.Map<DispatchDto, Dispatch>(dispatchDto);
                result = repairDAL.RepairDispatch(dispatch, applicationId);
            }
            if (String.Equals(workType, "故障诊断"))
            {
                diagnoseDispatch = Mapper.Map<DispatchDto, DiagnoseDispatch>(dispatchDto);
                result = repairDAL.DiagnoseDispatch(diagnoseDispatch, applicationId);
            }
            if (result)
            {
                return Content(new { msg = "成功", status = "success", phase = CurrentStatus.待维修.ToString() }.ToJsonString());
            }
            else
            {
                return Content(new { msg = "失败", status = "failed" }.ToJsonString());
            }
        }
        [HttpPost]
        public ActionResult Reject(int applicationId, string rejectReason)
        {
            var result = repairDAL.UpdateApplication(applicationId, rejectReason);
            if (result)
            {
                var data = new { msg = "已经成功驳回", status = "success", phase = CurrentStatus.已驳回.ToString() };
                return Content(data.ToJsonString());
            }
            else
            {
                return Content(new { msg = "驳回失败", status = "failed" }.ToJsonString());
            }
        }

        [HttpPost]
        public ActionResult CheckSelfRepairPlanByMngr(int selfRepairPlanId, string type, string msg)
        {
            bool result = false;
            if (string.Equals(type, "approve"))
            {
                result = repairDAL.ApproveSelfRepairPlan(selfRepairPlanId, msg);
            }
            if (string.Equals(type, "reject"))
            {
                result = repairDAL.RejectSelfRepairPlan(selfRepairPlanId, msg);
            }
            if (result)
            {
                string _phase = string.Empty;
                if (string.Equals(type, "approve"))
                { _phase = CurrentStatus.自修方案通过.ToString(); }
                if (string.Equals(type, "reject"))
                { _phase = CurrentStatus.自修方案失败.ToString(); }
                return Content(new { msg = "处理成功", status = "success", phase = _phase }.ToJsonString());
            }
            else
            {
                return Content(new { msg = "处理失败", status = "failed" }.ToJsonString());
            }
        }

        [HttpPost]
        public ActionResult CancelProcedure(string methodCategory, int categoryId)
        {
            bool result = repairDAL.CancelProcedure(methodCategory, categoryId);
            if (result)
            {
                return Content(new { msg = "处理成功", status = "success", phase = CurrentStatus.撤销成功.ToString() }.ToJsonString());
            }
            else
            {
                return Content(new { msg = "处理失败", status = "failed" }.ToJsonString());
            }
        }

        #endregion

        #region 维修申请处理---维修工程师
        public ActionResult Disposing()
        {
            return View();
        }

        public ActionResult NewRepairPlan()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreatOrUpdateSelfRepairPlanByEngr(int appId, int selfRepairPlanId, string steps, string tools, double timecost, string isspare, string spareparts, string type)
        {
            bool result = false;
            SelfRepairPlanDto selfRepairPlanDto = new SelfRepairPlanDto();
            selfRepairPlanDto.Step = steps;
            selfRepairPlanDto.Tool = tools;
            selfRepairPlanDto.TimeCost = timecost;

src/IMS.Web/Areas/Repair/Views/Repair/NewApplication.cshtml
@model IMS.Web.Dto.ApplicationDto
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>NewApplication</h2>
@section ContentBody{

    <div class="row ">
        <div class="col-lg-6 col-md-6 col-sm-6 col-lg-offset-3">
            @*@Html.DisplayNameFor(model => model.DeviceShortName)*@
            <label for="select_worksection">所属工段</label>
                <div>
                    <select id="select_worksection" class="dropdown form-control">
                        <option value="-1">请选择</option>
                    </select>
                </div>

                <label for="select_device">故障设备</label>
                <div>
                    <select id="select_device" class="dropdown form-control">
                        <option value="-1">请选择</option>
                    </select>
                </div>

                <label>发生时间</label>
                <div class='input-group date' id='div_fssj'>
                    <input type='text' id="txt_begintime" data-date-format="yyyy-mm-dd hh:ii" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>


                @{Html.RenderAction("SubSystem", "Common");}
            <span>故障类别</span>
            <select id="failuretype">
                <option value="-1">请选择</option>
                <option value="1">操作使用</option>
                <option value="2">维修保养</option>
                <option value="3">设计缺陷</option>
                <option value="4">设备老化</option>

            </select>

                <span><label>故障现象</label></span><textarea id="txtarea_appearance"></textarea>
                <span><label>故障描述</label></span><textarea id="txtarea_description"></textarea>
            </div>

        </div>

        <div class="row align-right">
            <div class="col-lg-6 col-md-6 col-sm-6  col-lg-offset-3">
                <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>重置</button>
                <button type="button" id="btn_submit" class="btn btn-primary" onclick="SubmitApplication()"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>提交</button>


            </div>

        </div>

        <script>
            $(function () {

                $('#div_fssj').datetimepicker({
                    //日期格式化，只显示日期
                    language: 'zh-CN',     //中文化
                    todayBtn: true,
                    pickerPosition: "bottom-left"
                });
                LoadWorkSectionNames();
                $("#select_worksection").change(function () {
                    LoadDeviceNames();
                });
            });

            function LoadWorkSectionNames() {
                $.post(
                    "/Repair/Common/GetWorkSectionNameList",
                    function (Data) {
                        $.each(Data.data, function (i, item) {
                            $("<option></option>").text(item["WorkSection"]).appendTo($("#select_worksection"));
                        })
                    });
            };

            function LoadDeviceNames() {
                $("#select_device").empty();
                $("<option></option>").val("-1").text("请选择").appendTo($("#select_device"));
                $.post(
                    "/Repair/Common/GetDeviceNamesBySection",
                    { sectionName: $("#select_worksection option:selected").text() },
                    function (Data) {
                        $.each(Data.data, function (i, item) {
                            $("<option></option>").val(item["DeviceNo"]).text(item["ShortName"]).appendTo($("#select_device"));
                        })
                    });
            };

            function SubmitApplication() {
                $.post(
                    "/Repair/Repair/CreatApplication",
                    {
                        deviceNo: $("#select_device option:selected").val(),
                        beginTime: $("#txt_begintime").val(),
                        failureAppearance: $("#txtarea_appearance").val(),
                        failureDescription: $("#txtarea_description").val(),
                        fstLevFailureLocation: $("#firstFailureLocation option:selected").text(),
                        secLevFailureLocation: $("#secondFailureLocation option:selected").text(),
                        thiLevFailureLocation: $("#thirdFailureLocation option:selected").text(),
                        failureType: $("#failuretype option:selected").text(),
                    },
                    function (Data) {
                        window.location.href = "/Repair/Repair/AllApplications";
                    }
                    );
            }
        </script>
}





src/IMS.Web/Areas/Repair/Views/Repair/ShowAllInOne.cshtml
@{
    Layout = null;
}
@using IMS.Web.Dto
@model SummarizeDto
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Summarize</title>
    <link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap/css/bootstrap-datetimepicker.css" rel="stylesheet" />
    <script src="~/Content/bootstrap/js/jquery-1.11.0.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap-datetimepicker.zh-CN.js"></script>

</head>
<body>
    <input type="hidden" id="sum_appid" value="@Model.ApplicationDto.Id" />
    <input type="hidden" id="sum_selfrepairid" value="@Model.ApplicationDto.SelfRepairPlanID" />
    <input type="hidden" id="sum_status" value="@Model.ApplicationDto.Status" />
    <div class="center-block" style="width:910px;height:760px;margin-top:5px">
        <div class="table-responsive">
            <table class="table table-bordered">
                <tr>
                    <td class="info">故障设备</td>
                    <td>@Model.ApplicationDto.DeviceShortName</td>
                    <td class="info">发生时间</td>
                    <td>@Model.ApplicationDto.BeginTime</td>
                    <td class="info">报修时间</td>
                    <td>@Model.ApplicationDto.ApplicationTime</td>
                </tr>
                <tr>
                    <td class="info">故障部位</td>
                    <td colspan="5">@Model.ApplicationDto.FullLocation</td>
                </tr>
                <tr>
                    <td class="info">故障描述</td>
                    <td colspan="5">@Model.ApplicationDto.FailureDescription</td>
                </tr>
                <tr>
                    <td class="info">故障现象</td>
                    <td colspan="5">@Model.ApplicationDto.FailureAppearance</td>
                </tr>
                <tr>
                    <td class="info">审核人</td>
                    <td>@Model.Dispatcher</td>
                    <td class="info">审核时间</td>
                    <td>@Model.DispatchTime</td>
                    <td class="info">审核结果</td>
                    <td></td>
                </tr>
                <tr>
                    <td class="info">维修（诊断）工程师</td>
                    <td>@Model.Engineer</td>
                    <td class="info">指示事项</td>
                    <td colspan="3">@Model.Instruction</td>
                </tr>
                <tr>
                    <td class="info">维修开始时间</td>
                    <td>
                        <div class='input-group date' id='div_fssj'>
                            <input type='text' id="sum_begintime" data-date-format="yyyy-mm-dd hh:ii" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </td>
                    <td class="info">维修用时</td>
                    <td>
                        <input type="text" id="sum_timecost" />
                    </td>
                    <td class="info">故障描述</td>
                    <td>
                        <textarea id="sum_description"></textarea>
                    </td>
                </tr>
                <tr>
                    <td class="info">一级故障部位</td>
                    <td>
                        <select id="firstFailureLocation">
                            <option value="-1">请选择</option>
                        </select>
                    </td>
                    <td class="info">二级故障部位</td>
                    <td>
                        <select id="secondFailureLocation">
                            <option value="-1">请选择</option>
                        </select>
                    </td>
                    <td class="info">三级故障部位</td>
                    <td>
                        <select id="thirdFailureLocation">
                            <option value="-1">请选择</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="info">故障现象</td>
                    <td colspan="5"><textarea id="sum_appearance">@Model.ApplicationDto.FailureAppearance</textarea></td>
                </tr>
                <tr>
                    <td class="info" rowspan="2">维修步骤</td>
                    <td colspan="5" rowspan="2"><textarea id="sum_steps">@Model.SelfRepairDto.Step</textarea> </td>
                </tr>
                <tr></tr>
                <tr>
                    <td class="info">维修工具</td>
                    <td colspan="3"><textarea id="sum_tools">@Model.SelfRepairDto.Tool</textarea></td>
                    <td class="info">备件信息</td>
                    <td colspan="3"><textarea id="sum_spareparts">@Model.SelfRepairDto.SparePartsInfo</textarea></td>
                </tr>
            </table>
        </div>
        <div style="text-align:right">

            <button type="button" class="btn btn-default" onclick="window.opener=null;window.close()"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>关闭</button>
            <button type="button" class="btn btn-success" onclick="summarize()"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span>提交</button>

        </div>
    </div>
    <script type="text/javascript">
        $(function () {
            IniteDropdownList();
            $("#firstFailureLocation").change(function () {
                GetSecondLevelSubSysList();
            });
            $('#div_fssj').datetimepicker({
                //日期格式化，只显示日期
                language: 'zh-CN',     //中文化
                todayBtn: true,
                pickerPosition: "bottom-left"
            });
        });

        function IniteDropdownList() {
            $.post(
            "/Repair/Common/GetSubSystemList",
            { lev: 0, parentId: 0 },
            function (Data) {
                $.each(Data.data, function (i, item) {
                    $("<option location=" + item["Name"] + "></option>").val(item["Id"]).text(item["Name"]).appendTo($("#firstFailureLocation"));
                });
                $("#firstFailureLocation option[location='@Model.ApplicationDto.FirstLocation']").attr("Selected", true);
                $.post("/Repair/Common/GetSubSystemList", { lev: 1, parentId: $("#firstFailureLocation").val() }, function (Data) {
                    $.each(Data.data, function (i, item) {
                        $("<option location=" + item["Name"] + "></option>").val(item["Id"]).text(item["Name"]).appendTo($("#secondFailureLocation"));
                    });
                    $("#secondFailureLocation option[location='@Model.ApplicationDto.SecondLocation']").attr("Selected", true);
                    $.post("/Repair/Common/GetSubSystemList", { lev: 2, parentId: $("#secondFailureLocation").val() }, function (Data) {
                        $.each(Data.data, function (i, item) {
                            $("<option location=" + item["Name"] + "></option>").val(item["Id"]).text(item["Name"]).appendTo($("#thirdFailureLocation"));
                        });
                        $("#thirdFailureLocation option[location='@Model.ApplicationDto.ThirdLocation']").attr("Selected", true);

                    });
                });
            });
        }




        function GetFirstLevelSubSysList() {
            $.post(
                "/Repair/Common/GetSubSystemList",
                { lev: 0, parentId: 0 },
                function (data) {
                    $.each(data, function (i, item) {
                        $("<option location=" + item["Name"] + "></option>").val(item["Id"]).text(item["Name"]).appendTo($("#firstFailureLocation"));
                    })
                });

        }
        function GetSecondLevelSubSysList() {
            $("#secondFailureLocation").empty();
            $("<option></option>").val("-1").text("请选择").appendTo($("#secondFailureLocation"));
            $("#thirdFailureLocation").empty();
            $("<option></option>").val("-1").text("请选择").appendTo($("#thirdFailureLocation"));
            $.post(
            "/Repair/Common/GetSubSystemList",
            { lev: 1, parentId: $("#firstFailureLocation").val() },
            function (data) {
                $.each(data, function (i, item) {
                    $("<option location=" + item["Name"] + "></option>").val(item["Id"]).text(item["Name"]).appendTo($("#secondFailureLocation"));
                })
            });
            $("#secondFailureLocation").change(function () {
                GetThirdLevelSubSysList();
            });
        }
        function GetThirdLevelSubSysList() {
            $("#thirdFailureLocation").empty();
            $("<option ></option>").val("-1").text("请选择").appendTo($("#thirdFailureLocation"));
            $.post(
            "/Repair/Common/GetSubSystemList",
            { lev: 2, parentId: $("#secondFailureLocation").val() },
            function (data) {
                $.each(data, function (i, item) {
                    $("<option location=" + item["Name"] + "></option>").val(item["Id"]).text(item["Name"]).appendTo($("#thirdFailureLocation"));
                })
            });
        }
        function summarize() {
            var beginTime = $("#sum_begintime").val();
            var timeCost = $("#sum_timecost").val();
            var description = $("#sum_description").val();
            var appearance = $("#sum_appearance").val();
            var steps = $("#sum_steps").val();
            var tools = $("#sum_tools").val();
            var partsInfo = $("#sum_spareparts").val();
            var fstLocation = $("#firstFailureLocation option:selected").text();
            var secLocation = $("#secondFailureLocation option:selected").text();
            var thiLocation = $("#thirdFailureLocation option:selected").text();
            $.post("/Repair/Repair/Summarize",
                {
                    appID: $("#sum_appid").val(),
                    selfRepairPlanId: $("#sum_selfrepairid").val(),
                    beginTime: $("#sum_begintime").val(),
                    timeCost: $("#sum_timecost").val(),
                    description: $("#sum_description").val(),
                    appearance: $("#sum_appearance").val(),
                    steps: $("#sum_steps").val(),
                    tools: $("#sum_tools").val(),
                    partsInfo: $("#sum_spareparts").val(),
                    fstLocation: $("#firstFailureLocation option:selected").text(),
                    secLocation: $("#secondFailureLocation option:selected").text(),
                    thiLocation: $("#thirdFailureLocation option:selected").text()
                },
            function (Data) {
                data = $.parseJSON(Data);
                if (data.status == "success") {
                    alert(data.msg);
                    window.opener = null; window.close();
                }
            });
        }
    </script>
</body>

</html>