src/IMS.Web/Controllers/Failure/FailureController.cs

using IMS.Data.Services;
using IMS.Json;
using IMS.Model.ViewModel;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Linq;

namespace IMS.Web.Controllers.Failure
{
    public class FailureController : Controller
    {
        //
        // GET: /Failure/

        private FailureService failureService = new FailureService();
        public ActionResult NewApplication()
        {
            return View();
        }

        public ActionResult AllApplications()
        {
            return View();
        }


        public void AddNewApplication()
        {
            MaintenanceApplicationViewModel MaintenanceApplicationVM = new MaintenanceApplicationViewModel();
            MaintenanceApplicationVM.DeviceNo = Request.Params["deviceNo"];
            MaintenanceApplicationVM.BeginTime = Convert.ToDateTime(Request.Params["beginTime"]);
            MaintenanceApplicationVM.FailureAppearance = Request.Params["failureAppearance"];
            MaintenanceApplicationVM.FailureDescription = Request.Params["failureDescription"];
            MaintenanceApplicationVM.FstLevFailureLocation = Request.Params["fstLevFailureLocation"];
            MaintenanceApplicationVM.SecLevFailureLocation = Request.Params["secLevFailureLocation"];
            MaintenanceApplicationVM.ThiLevFailureLocation = Request.Params["thiLevFailureLocation"];
            MaintenanceApplicationVM.ReporterId = "报告人A";
            MaintenanceApplicationVM.ReportTime = DateTime.Now;
            MaintenanceApplicationVM.Status = "审核中";
            MaintenanceApplicationVM.Modifiable = 0;
            failureService.AddNewFailure(MaintenanceApplicationVM);

        }

        public ActionResult UpDateApplication()
        {
            MaintenanceApplicationViewModel MaintenanceApplicationVM = new MaintenanceApplicationViewModel();
            int id = Convert.ToInt32(Request.Params["applicationId"]);
            MaintenanceApplicationVM.FailureAppearance = Request.Params["failureAppearance"];
            MaintenanceApplicationVM.FailureDescription = Request.Params["failureDescription"];
            MaintenanceApplicationVM.FstLevFailureLocation = Request.Params["fstLevFailureLocation"];
            MaintenanceApplicationVM.SecLevFailureLocation = Request.Params["secLevFailureLocation"];
            MaintenanceApplicationVM.ThiLevFailureLocation = Request.Params["thiLevFailureLocation"];
            MaintenanceApplicationVM.ReportTime = DateTime.Now;
            bool result = failureService.UpDateApplication(id, MaintenanceApplicationVM);
            if (result)
            {
                return Content(new { msg = "成功", status = "success" }.ToJsonString());
            }
            else
            {
                return Content(new { msg = "失败", status = "failed" }.ToJsonString());
            }

        }

        public ActionResult DeleteApplication()
        {
            int id = Convert.ToInt32(Request.Params["applicationId"]);
            var result = failureService.DeleteApplicationById(id);
            if (result)
            {
                return Content(new { msg = "删除成功", status = "success" }.ToJsonString());
            }
            else
            {
                return Content(new { msg = "删除失败", status = "failed" }.ToJsonString());
            }
        }


        public ActionResult GetAllApplicationsByUserName(string name, int limit, int offset, string sectionName, string deviceNo, string beginTime, string endTime, string ordername)
        {
            var AllApplicationsList = CommonService.GetAllApplicationsByName(name, sectionName, deviceNo, beginTime, endTime);
            if (AllApplicationsList != null)
            {
                var total = AllApplicationsList.Count;
                var rows = AllApplicationsList.Skip(offset).Take(limit).ToList();
                var d = new { total = total, rows = rows };
                return Content(d.ToJsonString());
            }
            else
                return Json("");
        }








        /// <summary>
        /// 测试功能的
        /// </summary>
        /// <returns></returns>
        public ActionResult GetDepartment()
        {
            return View();
        }


        public JsonResult GetDepartment1()
        {
            var lstRes = new List<DeviceViewModel>();
            for (var i = 0; i < 50; i++)
            {
                var oModel = new DeviceViewModel();
                oModel.DeviceNo = i.ToString();
                oModel.DeviceName = Guid.NewGuid().ToString();
                lstRes.Add(oModel);
            }

            var total = lstRes.Count;
            var rows = lstRes;
            return Json(new { total = total, rows = rows }, JsonRequestBehavior.AllowGet);
        }


    }
}

src/IMS.Web/Controllers/Partial/PartialController.cs
using IMS.Data.Services;
using IMS.Model.Model;
using IMS.Model.ViewModel;
using System.Collections.Generic;
using System.Web.Mvc;

namespace IMS.Web.Controllers.Partial
{
    public class PartialController : Controller
    {
        //
        // GET: /Partial/

        FailureService failureService = new FailureService();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SubSystem()
        {
            return PartialView();
        }
        public ActionResult EngineerSelect()
        {
            return PartialView();
        }

        public ActionResult SearchBar() 
        {
            return PartialView();
        }
        public JsonResult GetSubSystemList(int lev, int parentId)
        {
            if (lev != -1)
            {
                IEnumerable<SubSystem> subSystemList = failureService.GetSubSystemList(lev, parentId);
                if (subSystemList != null)
                {
                    return Json(subSystemList);
                }
            }
            return Json("");
        }
        public ActionResult GetName(string type, string teamName)
        {
            List<EngineerViewModel> engineerVMList = CommonService.GetName(type, teamName);
            if (engineerVMList != null)
            {
                return Json(engineerVMList);
            }
            else
                return Json("");

        }

        public JsonResult GetWorkSectionNameList() 
        {
            List<DeviceViewModel> deviceVMList =CommonService.GetWorkSectionNameList();
            if (deviceVMList != null)
            {
                return Json(deviceVMList);
            }
            else
            {
                return Json("");
            }
        }

        public JsonResult GetDeviceNamesBySection(string sectionName) 
        {
            List<DeviceViewModel> deviceVMList = CommonService.GetDeviceNamesBySection(sectionName);
            if (deviceVMList != null)
            {
                return Json(deviceVMList);
            }
            else
            {
                return Json("");
            }
        }
    }
}

src/IMS.Web/Views/Failure/NewApplication.cshtml
@{
    ViewBag.Title = "NewApplication";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FailureReport</h2>

@section ContentBody{

    <div class="row ">
        <div class="col-lg-6 col-md-6 col-sm-6 col-lg-offset-3">
            <label for="select_worksection">所属工段</label>
            <div>
                <select id="select_worksection" class="dropdown form-control">
                    <option value="-1">请选择</option>
                </select>
            </div>

            <label for="select_device">故障设备</label>
            <div>
                <select id="select_device" class="dropdown form-control">
                    <option value="-1">请选择</option>
                </select>
            </div>

            <label>发生时间</label>
            <div class='input-group date' id='div_fssj'>
                <input type='text' id="txt_begintime" data-date-format="yyyy-mm-dd hh:ii" />
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>


            @{Html.RenderAction("SubSystem", "Partial");}
            <span><label>故障现象</label></span><textarea id="txtarea_appearance"></textarea>
            <span><label>故障描述</label></span><textarea id="txtarea_description"></textarea>
        </div>

    </div>

    <div class="row align-right">
        <div class="col-lg-6 col-md-6 col-sm-6  col-lg-offset-3">
            <button type="button" class="btn btn-default"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>重置</button>
            <button type="button" id="btn_submit" class="btn btn-primary" onclick="SubmitFailure()"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>提交</button>


        </div>

    </div>

    <script>
        $(function () {

            $('#div_fssj').datetimepicker({
                //日期格式化，只显示日期
                language: 'zh-CN',     //中文化
                todayBtn: true,
                pickerPosition: "bottom-left"
            });
            LoadWorkSectionNames();
            $("#select_worksection").change(function () {
                LoadDeviceNames();
            });
        });

        function LoadWorkSectionNames() {
            $.post(
                "/Partial/GetWorkSectionNameList",
                function (data) {
                    $.each(data, function (i, item) {
                        $("<option></option>").text(item["WorkSection"]).appendTo($("#select_worksection"));
                    })
                });
        };

        function LoadDeviceNames() {
            $("#select_device").empty();
            $("<option></option>").val("-1").text("请选择").appendTo($("#select_device"));
            $.post(
                "/Partial/GetDeviceNamesBySection",
                { sectionName: $("#select_worksection option:selected").text() },
                function (data) {
                    $.each(data, function (i, item) {
                        $("<option></option>").val(item["DeviceNo"]).text(item["DeviceName"]).appendTo($("#select_device"));
                    })
                });
        };

        function SubmitFailure() {
            $.post(
                "/Failure/AddNewApplication",
                {
                    deviceNo: $("#select_device option:selected").val(),
                    beginTime: $("#txt_begintime").val(),
                    failureAppearance: $("#txtarea_appearance").val(),
                    failureDescription: $("#txtarea_description").val(),
                    fstLevFailureLocation: $("#firstFailureLocation option:selected").text(),
                    secLevFailureLocation: $("#secondFailureLocation option:selected").text(),
                    thiLevFailureLocation: $("#thirdFailureLocation option:selected").text(),
                },
                function (data) {
                    window.location.href = "/Failure/AllApplications";
                }
                );
        }
    </script>
}



